name: TRICK A4IF WORKER BOT

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    
    steps:
      # ১. এই অংশটিই আপনার প্রাইভেট মাস্টার গিটহাব থেকে কোড ধার করে আনবে!
      - name: Fetch Code from Master Repo
        uses: actions/checkout@v4
        with:
          repository: arifyoutubeshorts-max/Trick-A4IF-Master
          token: ${{ secrets.MASTER_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Initialize & Install Core Dependencies
        run: |
          npm init -y
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth telegraf fs-extra node-fetch@2

      # ২. ধার করা কোডটি এখন রান করবে
      - name: Ignite TRICK A4IF Worker
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: node engine.obfuscated.js
